### ISSUE TITLE
pod install fails after updating Xcode to 16.3

### ISSUE THREAD

**Issue by cloudhx** [nativescript-community/sentry#28]
Hello, after I updated the Xcode to 16.3, I cannot build the project using sentry, it complains as below. Could anyone shed some light on it? Thanks a lot!

```
Installing pods...
Analyzing dependencies
Pre-downloading: `Sentry` from `https://github.com/getsentry/sentry-cocoa.git`, tag `8.48.0`
[!] Failed to load 'Sentry' podspec: 
[!] Invalid `SentryPrivate.podspec` file: undefined method `visionos' for #<Pod::Specification name="SentryPrivate">.

 #  from /var/folders/fh/whm9qhd94qzd5fm_c1f6yp4h0000gn/T/d20250617-93682-prb7rx/SentryPrivate.podspec:22
 #  -------------------------------------------
 #    s.watchos.deployment_target = "4.0"
 >    s.visionos.deployment_target = "1.0"
 #    s.module_name  = "SentryPrivate"
 #  -------------------------------------------

'pod install' command failed.
```

Running `ns doctor ios` shows below

```
❯ ns doctor ios
✔ Getting environment information 

No issues were detected.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ Xcode version 16.3.0 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.9.2 version and is up to date.
✔ Component @nativescript/core has 8.9.2 version and is up to date.
✔ Component @nativescript/ios has 8.9.2 version and is up to date.
```

I'm using the latest version of the package
```
❯ npm list @nativescript-community/sentry
app@ /Users/company/Documents/workspaces/company/app
└── @nativescript-community/sentry@4.6.39
```
